#!/bin/bash

# You can execute me through Glide by doing the following:
# - Execute `glide slow`
# - ???
# - Profit

pushd $GOPATH/src/appscode.com/kubed

# bust glide cache
rm -rf ~/.glide/cache/{info,src}/git-diffusion.appscode.com-appscode-37-api*
rm -rf ~/.glide/cache/{info,src}/git-diffusion.appscode.com-appscode-39-client*
rm -rf ~/.glide/cache/{info,src}/git-diffusion.appscode.com-appscode-40-data*
rm -rf ~/.glide/cache/{info,src}/git-diffusion.appscode.com-appscode-38-appctl*

glide up -v
glide vc --only-code --no-tests

popd
