// +build !ignore_autogenerated

/*
Copyright 2018 The Kubed Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by conversion-gen. DO NOT EDIT.

package v1alpha1

import (
	unsafe "unsafe"

	kubed "github.com/appscode/kubed/apis/kubed"
	conversion "k8s.io/apimachinery/pkg/conversion"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func init() {
	localSchemeBuilder.Register(RegisterConversions)
}

// RegisterConversions adds conversion functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterConversions(s *runtime.Scheme) error {
	if err := s.AddGeneratedConversionFunc((*ResultEntry)(nil), (*kubed.ResultEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_ResultEntry_To_kubed_ResultEntry(a.(*ResultEntry), b.(*kubed.ResultEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubed.ResultEntry)(nil), (*ResultEntry)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubed_ResultEntry_To_v1alpha1_ResultEntry(a.(*kubed.ResultEntry), b.(*ResultEntry), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*SearchResult)(nil), (*kubed.SearchResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_v1alpha1_SearchResult_To_kubed_SearchResult(a.(*SearchResult), b.(*kubed.SearchResult), scope)
	}); err != nil {
		return err
	}
	if err := s.AddGeneratedConversionFunc((*kubed.SearchResult)(nil), (*SearchResult)(nil), func(a, b interface{}, scope conversion.Scope) error {
		return Convert_kubed_SearchResult_To_v1alpha1_SearchResult(a.(*kubed.SearchResult), b.(*SearchResult), scope)
	}); err != nil {
		return err
	}
	return nil
}

func autoConvert_v1alpha1_ResultEntry_To_kubed_ResultEntry(in *ResultEntry, out *kubed.ResultEntry, s conversion.Scope) error {
	out.Score = in.Score
	out.Object = in.Object
	return nil
}

// Convert_v1alpha1_ResultEntry_To_kubed_ResultEntry is an autogenerated conversion function.
func Convert_v1alpha1_ResultEntry_To_kubed_ResultEntry(in *ResultEntry, out *kubed.ResultEntry, s conversion.Scope) error {
	return autoConvert_v1alpha1_ResultEntry_To_kubed_ResultEntry(in, out, s)
}

func autoConvert_kubed_ResultEntry_To_v1alpha1_ResultEntry(in *kubed.ResultEntry, out *ResultEntry, s conversion.Scope) error {
	out.Score = in.Score
	out.Object = in.Object
	return nil
}

// Convert_kubed_ResultEntry_To_v1alpha1_ResultEntry is an autogenerated conversion function.
func Convert_kubed_ResultEntry_To_v1alpha1_ResultEntry(in *kubed.ResultEntry, out *ResultEntry, s conversion.Scope) error {
	return autoConvert_kubed_ResultEntry_To_v1alpha1_ResultEntry(in, out, s)
}

func autoConvert_v1alpha1_SearchResult_To_kubed_SearchResult(in *SearchResult, out *kubed.SearchResult, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Hits = *(*[]kubed.ResultEntry)(unsafe.Pointer(&in.Hits))
	out.Total = in.Total
	out.MaxScore = in.MaxScore
	out.Took = in.Took
	return nil
}

// Convert_v1alpha1_SearchResult_To_kubed_SearchResult is an autogenerated conversion function.
func Convert_v1alpha1_SearchResult_To_kubed_SearchResult(in *SearchResult, out *kubed.SearchResult, s conversion.Scope) error {
	return autoConvert_v1alpha1_SearchResult_To_kubed_SearchResult(in, out, s)
}

func autoConvert_kubed_SearchResult_To_v1alpha1_SearchResult(in *kubed.SearchResult, out *SearchResult, s conversion.Scope) error {
	out.ObjectMeta = in.ObjectMeta
	out.Hits = *(*[]ResultEntry)(unsafe.Pointer(&in.Hits))
	out.Total = in.Total
	out.MaxScore = in.MaxScore
	out.Took = in.Took
	return nil
}

// Convert_kubed_SearchResult_To_v1alpha1_SearchResult is an autogenerated conversion function.
func Convert_kubed_SearchResult_To_v1alpha1_SearchResult(in *kubed.SearchResult, out *SearchResult, s conversion.Scope) error {
	return autoConvert_kubed_SearchResult_To_v1alpha1_SearchResult(in, out, s)
}
