apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubed-operator
  namespace: kube-system
  labels:
    app: kubed
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kubed
    spec:
      containers:
      - name: kubed
        image: appscode/kubed:0.6.0-rc.0
        imagePullPolicy: IfNotPresent
        args:
        - run
        - --v=3
        - --api.address=:8080
        - --web.address=:56790
        ports:
        - containerPort: 8080
          name: api
          protocol: TCP
        - containerPort: 56790
          name: web
          protocol: TCP
        volumeMounts:
          - name: config
            mountPath: /srv/kubed
          - name: scratch
            mountPath: /tmp
          - name: snapshot
            mountPath: /var/data
      volumes:
        - name: config
          secret:
            secretName: kubed-config
        - name: scratch
          emptyDir: {}
        - name: snapshot
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: kubed-operator
  namespace: kube-system
  labels:
    app: kubed
spec:
  ports:
  - name: api
    port: 8080
    targetPort: api
  - name: web
    port: 56790
    targetPort: web
  selector:
    app: kubed
