apiVersion: v1
kind: Service
metadata:
  name: {{ template "config-syncer.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-syncer.labels" . | nindent 4 }}
spec:
  ports:
  # Port used to expose admission webhook apiserver
  - name: api
    port: 443
    targetPort: {{ default "8443" .Values.apiserver.securePort }}
  selector:
    {{- include "config-syncer.selectorLabels" . | nindent 4 }}
